import {
  Play, Pause, Square, Check, X, ArrowLeft, ArrowRight,
  Plus, Pencil, Trash2, MoreVertical, ChevronDown, ChevronUp,
  ChevronRight, Search, Share2, Map, Calendar, Wifi, WifiOff,
  AlertTriangle, Info, CheckCircle, XCircle, RefreshCw,
  Eye, EyeOff, Upload, Download, Settings, User, Bell,
  Heart, Activity, Zap, Clock, BarChart2, TrendingUp,
  TrendingDown, Minus, Lock, Unlock, Star, Flag,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export const uiIcons = {
  play: Play,
  pause: Pause,
  stop: Square,
  check: Check,
  close: X,
  back: ArrowLeft,
  forward: ArrowRight,
  add: Plus,
  edit: Pencil,
  delete: Trash2,
  more: MoreVertical,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-right': ChevronRight,
  search: Search,
  share: Share2,
  map: Map,
  calendar: Calendar,
  wifi: Wifi,
  'wifi-off': WifiOff,
  warning: AlertTriangle,
  info: Info,
  'check-circle': CheckCircle,
  'x-circle': XCircle,
  refresh: RefreshCw,
  eye: Eye,
  'eye-off': EyeOff,
  upload: Upload,
  download: Download,
  settings: Settings,
  user: User,
  bell: Bell,
  heart: Heart,
  activity: Activity,
  zap: Zap,
  clock: Clock,
  chart: BarChart2,
  'trend-up': TrendingUp,
  'trend-down': TrendingDown,
  minus: Minus,
  lock: Lock,
  unlock: Unlock,
  star: Star,
  flag: Flag,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof uiIcons;
