export type {
  ExerciseCategory,
  Exercise,
  StrengthSet,
  CardioSet,
  SetEntry,
  Block,
  TrainingSession,
  TrainingLogState,
  TrainingLogEvent,
  TrainingLogCommand,
  StartSession,
  AddBlock,
  LogStrengthSet,
  LogCardioSet,
  FinishSession,
  DeleteSession,
  UpdateBlockNote,
  UpdateSessionNote,
  ChangeSetType,
  LogRPE,
  ToggleSetFailed,
  SetBlockType,
  SetBlockRounds,
  RemoveSet,
  UpdateSet,
  UpdateSetComment,
  SetBlockRest,
  RenameSession,
  UpdateSessionStartTime,
  ReorderBlocks,
  AddToSuperset,
  LeaveSuperset,
  RemoveBlock,
} from './domain/types';

export type {
  ActiveSessionView,
  SessionHistoryItem,
  EditingSessionsView,
  RecentExercise,
} from './projections';

export {
  handleStartSession,
  handleAddBlock,
  handleLogStrengthSet,
  handleLogCardioSet,
  handleFinishSession,
  handleDeleteSession,
  handleUpdateBlockNote,
  handleUpdateSessionNote,
  handleChangeSetType,
  handleLogRPE,
  handleToggleSetFailed,
  handleSetBlockType,
  handleSetBlockRounds,
  handleRemoveSet,
  handleUpdateSet,
  handleUpdateSetComment,
  handleSetBlockRest,
  handleRenameSession,
  handleUpdateSessionStartTime,
  handleReorderBlocks,
  handleAddToSuperset,
  handleLeaveSuperset,
  handleRemoveBlock,
  handleUpdateTrainingSession,
} from './commands/handlers';

export {
  getActiveSession,
  getSessionHistory,
  getEditingSession,
  getRecentExercises,
} from './queries';

export {
  activeSessionProjection,
  sessionHistoryProjection,
  editingSessionProjection,
  recentExercisesProjection,
} from './projections';
